### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by iamlaksh1** [Esri/azure-for-geoevent#2]
Hi Esri Geoevent team,

Apologies me on this basic question.  I am new to Java and maven world. This is my first experience with building custom connector. As part of one of my requirement, I am trying build this connector as per guide. I have successfully installed maven and when I try to run install command 

Since am running this command in windows server - I guessed this may be proxy issue, I tried editing 
E:\maven\apache-maven-3.6.0\conf\settings.xml to include user name, proxy and host and port . I know this works, because I can access the maven plugin path

But still I see the error. Please help me if I miss something . 

<proxies>   
    <proxy>
      <id>optional</id>
      <active>true</active>
      <protocol>http</protocol>
      <username>user</username>
      <password>xxx</password>
      <host>proxyserver.proxy.domain.net</host>
      <port>8080</port>
      <nonProxyHosts>repo.maven.apache.org</nonProxyHosts>
    </proxy>    
  </proxies>

![mvn error](https://user-images.githubusercontent.com/5049814/53217169-af53ce00-361c-11e9-9389-4ae9ecfa9065.JPG)

**Comment by hanoch** [comment]
Make sure you are connected to the internet and can access the central maven repository urls, e.g.: 
- http://repo.maven.apache.org/maven2/com/esri/geoevent/sdk/geoevent-sdk
- http://central.maven.org/maven2/com/esri/geoevent/sdk/geoevent-sdk/
- http://repo1.maven.org/maven2/com/esri/geoevent/sdk/geoevent-sdk/

**Comment by eironside** [comment]
@iamlaksh1 Did this fix your issue? Can I close this issue? - Thanks!

**Comment by iamlaksh1** [comment]
@eironside  - yes. we compiled the code and works. Thank you a ton. I have few more questions, recently our geoevent went rogue, did a admin reset with Esri support. Once geoevent is back, our event hub adaptors went missing. JAR files are loaded from geoevent manager , java path are in-tact, but still adaptor not visible. What would went wrong?
